config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root "items#index"

  resources :items, only: [:index, :show]
  resource :cart, only: [:show, :update, :destroy]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/alert.rb
class Alert < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/item.rb
class Item < ApplicationRecord
  validates_presence_of :name
  has_many :item_prices, dependent: :destroy

  enum category: {
    "Bourbon" => 0,
    "Rum" => 1,
    "Gin" => 2,
    "Brandy" => 3,
    "Cognac" => 4,
    "Vermouth" => 5,
    "Tequila" => 6,
    "Mezcal" => 7,
    "Liqueur" => 8,
    "Whisky" => 9,
    "Absinthe" => 10,
    "Sake" => 11,
    "Armagnac" => 12,
    "Wine" => 13
  }

  def availability
    amount = item_prices.found.size

    if amount == 1
      "Znaleźliśmy w 1 sklepie"
    else
      "Znaleźliśmy w #{amount} sklepach"
    end
  end

  def lowest_price
    item_prices.found.minimum(:price)
  end
end

app/models/item_price.rb
class ItemPrice < ApplicationRecord
  belongs_to :item
  belongs_to :vendor

  validates_uniqueness_of :item_id, scope: :vendor_id

  scope :found, -> { where.not(price: nil) }

  def absolute_url
    return unless url

    vendor.url + url
  end
end

app/models/potential_item.rb
class PotentialItem < ApplicationRecord
  validates_presence_of :name, :url
  validates :name, uniqueness: { scope: :vendor }
  belongs_to :vendor

  enum category: Item.categories
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  include ImageUploader::Attachment(:image)

  validates_presence_of :name, :url
  validates_uniqueness_of :name, :url
  has_many :item_prices, dependent: :destroy
  has_many :potential_items, dependent: :destroy

  def self.forfiter
    find_by(sys_name: "forfiter")
  end

  def self.dom_whisky
    find_by(sys_name: "dom_whisky")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_cart
  include Pagy::Backend

  def set_cart
    cookies[:cart] = [].to_json if cookies[:cart].blank?
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_item, only: :update

  def update
    add_cart_item

    Turbo::StreamsChannel.broadcast_replace_to(
      "cart_stream",
      target: "cart_items",
      html: render(partial: "carts/cart")
    )
  end

  def show
    @vendors = Carts::Compare.new(
      JSON.parse(cookies[:cart])
    ).call
    @q = Item.ransack(params[:q])
  end

  def destroy
    cookies[:cart] = [].to_json

    Turbo::StreamsChannel.broadcast_replace_to(
      "cart_stream",
      target: "cart_items",
      html: render(partial: "carts/cart")
    )
  end

  private

  def add_cart_item
    existing_items = JSON.parse(cookies[:cart])

    if existing_items.blank?
      new_item = [@item.id, @item.name, 1]
      cookies[:cart] = [new_item].to_json
      return
    end

    my_item = existing_items.find do |existing_item|
      existing_item[0] == @item.id
    end

    if my_item
      cookies[:cart] = existing_items.tap do
        my_item = existing_items.find do |existing_item|
          existing_item[0] == @item.id
        end

        my_item[2] += 1 if my_item
      end.to_json
    else
      cookies[:cart] = existing_items.push([@item.id, @item.name, 1]).to_json
    end

  rescue JSON::ParserError
    cookies[:cart] = [].to_json
    return
  end

  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: :show

  def index
    @q = Item.ransack(params[:q])
    items = @q.result(distinct: true)

    @pagy, @items = pagy(items)
  end

  def show
    @q = Item.ransack(params[:q])
    @item_prices = @item.item_prices.found.includes(:vendor)
  end

  private

  def set_item
    @item ||= Item.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/application/_menu.erb
<div class="menu-wrapper">
  <div class="menu--header">
    Kategorie
  </div>
  <div class="menu--content">
    <% Item.categories.keys.each do |category| %>
      <div class="menu--item"><%= category %></div>
    <% end %>
  </div>
</div>

app/views/carts/_cart.erb
<div id="cart_items" data-controller="cart" %>
  <ul class="cart--items">
    <% if JSON.parse(cookies[:cart]).blank? %>
      Twój koszyk jest pusty
    <% else %>
      <% JSON.parse(cookies[:cart]).each do |cart_item| %>
        <%= render "carts/cart_item", cart_item: cart_item %>
      <% end %>
  <% end %>
  </ul>
  <% unless JSON.parse(cookies[:cart]).blank? %>
    <div  class="cart--actions">
      <div class="cart--compare">
        <%= link_to "Porównaj ceny", cart_path, class: "btn btn-primary main-button" %>
      </div>
      <div class="cart--clear" data-action="click->cart#clearCart">
        Wyczyść koszyk
      </div>
    </div>
  <% end %>
</div>

app/views/carts/_cart_item.erb
<li id=<%= cart_item[0]%> class="cart--item"><%= cart_item[1]%><span class="bold">  x<%= cart_item[2]%></span></li>

app/views/carts/_index.erb
<div class="cart-wrapper" data-controller="cart">
  <div class="cart--header">Koszyk</div>
  <%= turbo_stream_from 'cart_stream' %>
  <%= render "carts/cart" %>
</div>

app/views/carts/show.erb
<%= render "items/item_search" %>

<div class="comparisons-wrapper" data-controller="cart">
  <% @vendors.each do |vendor| %>
    <div class="comparison">
      <div class="comparison--left">
        <div class="vendor--image">
          <% if vendor[:image_url] %>
            <%= image_tag(vendor[:image_url]) %>
          <% end %>
        </div>
      </div>
      <div class="comparison--middle">
        <ul class="comparison--items">
          <% vendor[:found].each do |found_item| %>
            <li class="comparison-item__found" %>
              <div class="comparison-item--name">
                <%= found_item[:item] %><span class="bold"> x<%= found_item[:amount]%></span>
              </div>
              <div class="comparison-item--price" %>
                - <%= number_to_currency(found_item[:price], unit: "PLN", separator: ",", delimiter: " ", format: "%n %u")%>
              </div>
            </li>
          <% end %>
          <% vendor[:not_found].each do |missing_item| %>
            <li class="comparison-item__not-found" %>
              <div class="comparison-item--name">
                <%= missing_item %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
      <div class="comparison--right">
        <div class="comparison--final-price" %>
          <%= number_to_currency(vendor[:final_amount], unit: "PLN", separator: ",", delimiter: " ", format: "%n %u")%>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/items/_item_search.erb
<div class="items-search">
  <%= search_form_for @q do |f| %>
    <%= f.search_field :name_cont, class: "items-search__input", placeholder: "Wyszukaj spośród #{Item.all.size} produktów..." %>
  <% end %>
</div>

app/views/items/index.html.erb
<%= render "item_search" %>

<div class="items-wrapper" data-controller="cart">
  <% @items.each do |item| %>
    <div class="item">
      <% if item.image_url %>
        <div class="item--left__with-img">
          <div class="item--image-wrapper">
            <%= image_tag(item.image_url, class: "item--image") %>
          </div>
          <div class="item--image-side" %>
            <div class="item--name"><%= item.name %></div>
            <div class="item--availability"><%= item.availability %></div>
          </div>
        </div>
        <div class="item--right">
          <div class="item--price-wrapper__with-img">
            <div class="item--prices">
              <%= link_to "Sprawdź ceny", item_path(item), class: "btn btn-primary main-button" %>
            </div>
            <div class="item--lowest" %>
              <%= "Najtaniej: #{number_to_currency(item.lowest_price, unit: "PLN", separator: ",", delimiter: " ", format: "%n %u")}" %>
            </div>
          </div>
          <div data-action="click->cart#addItem"><%= image_tag("cart.png", class: "item--cart-icon", value: item.id)%></div>
        </div>
      <% else %>
        <div class="item--left">
          <div class="item--name"><%= item.name %></div>
          <div class="item--availability"><%= item.availability %></div>
        </div>
        <div class="item--right">
          <div class="item--price-wrapper">
            <div class="item--prices">
              <%= link_to "Sprawdź ceny", item_path(item), class: "btn btn-primary main-button" %>
            </div>
            <div class="item--lowest" %>
              <%= "Najtaniej: #{number_to_currency(item.lowest_price, unit: "PLN", separator: ",", delimiter: " ", format: "%n %u")}" %>
            </div>
          </div>
          <div data-action="click->cart#addItem"><%= image_tag("cart.png", class: "item--cart-icon", value: item.id)%></div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<%== pagy_nav(@pagy) %>

app/views/items/show.html.erb
<%= render "item_search" %>
<div class="vendors-wrapper">
  <% @item.item_prices.found.each do |item_price| %>
    <div class="vendor">
      <div class="vendor--left">
        <div class="vendor--image">
          <% if item_price.vendor.image_data %>
            <%= link_to image_tag(item_price.vendor.image_url), item_price.vendor.url, target: "_blank" %>
          <% end %>
        </div>
      </div>
      <div class="vendor--right">
        <div class="vendor--price">
          <%= number_to_currency(item_price.price, unit: "PLN", separator: ",", delimiter: " ", format: "%n %u") %>
        </div>
        <div class="vendor--link">
          <%= link_to "Przejdź do sklepu", item_price.absolute_url, class: "btn btn-primary main-button", target: "_blank" %>
        </div>
        <div class="vendor--updated-at">
          <%= "Ostatnia aktualizacja: #{item_price.updated_at.strftime('%d/%m/%Y %H:%M')}" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PubCrawl</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "menu" %>
    <div class="main-wrapper">
      <%= yield %>
    </div>
    <%= render "carts/index" %>
  </body>
</html>